"""init

Revision ID: afacbca20615
Revises: 
Create Date: 2026-06-26 08:00:27.568848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afacbca20615'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suumo_building_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True, comment='築年数（年）'),
    sa.Column('total_floors', sa.Integer(), nullable=True, comment='建物総階数'),
    sa.Column('station_distance', sa.Integer(), nullable=True, comment='駅徒歩分'),
    sa.Column('building_type', sa.String(length=32), nullable=True, comment='マンション・アパート・一軒家'),
    sa.Column('building_structure', sa.String(length=32), nullable=True, comment='RC・SRC・木造・鉄骨など。詳細ページから取得。NULL許容'),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suumo_building_id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('suumo_room_id', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True, comment='賃料（円）'),
    sa.Column('admin_fee', sa.Integer(), nullable=True, comment='管理費（円）'),
    sa.Column('monthly_fee', sa.Integer(), nullable=True, comment='price + admin_fee（円）'),
    sa.Column('deposit', sa.Integer(), nullable=True, comment='敷金（円）'),
    sa.Column('key_money', sa.Integer(), nullable=True, comment='礼金（円）'),
    sa.Column('liv_area', sa.Float(), nullable=True, comment='専有面積（㎡）'),
    sa.Column('floor', sa.Integer(), nullable=True, comment='部屋の階数'),
    sa.Column('floor_plan', sa.String(length=16), nullable=True, comment='間取り（例: 1LDK）'),
    sa.Column('estimated_price', sa.Integer(), nullable=True, comment='適正価格（円）。モデル実行後に保存'),
    sa.Column('divergence_rate', sa.Float(), nullable=True, comment='裁定スコア = (market - estimated) / estimated'),
    sa.Column('brand_score', sa.Float(), nullable=True, comment='LLMブランドスコア（Phase2）'),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suumo_room_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('buildings')
    # ### end Alembic commands ###
